### ISSUE TITLE
[question] Multifasta file

### ISSUE THREAD

**Issue by martynakgajos** [abcsFrederick/non-B_gfa#1]
Is it possible to run the program on multifasta file (e.g. with all of the chromosomes)?
If yes, which parameters do I have to adjust? For now, I am getting results only for the first chromosome in the file ("chr1").

**Comment by Brian-Luke** [comment]
If you take the example input (gfa_test.fasta) and change the first line from
>Test Sequence
to
>chr1
and then copy all of the lines to the end of the file (without a blank line between them) and change the second header line to
>chr2
and run this file, you will see that it works fine using the default parameters
gfa -skipWGET -seq (input fasta file) -out (prefix for output files).

Please realize that the DNA sequence is by default limited to 300,000,000 nucleotides. If your "chr1" is larger then that, you will have to edit the line
#define MAX_DNA 300000000
in gfa.h and recompile the program.
