### ISSUE TITLE
NCBI Web Server that uses this program fails due to CAPTCHA not working

### ISSUE THREAD

**Issue by rsharris** [abcsFrederick/non-B_gfa#3]
The search tool at https://nonb-abcc.ncifcrf.gov/apps/nBMST/default is protected by a CATCHA that doesn't work on any of the 3 web browsers I tried (Safari, Firefox, Chrome). The problem is it wants me to type in the characters in an image it thinks it is showing me. But the image is not visible.

I realize reporting this in this repo is odd. You might ask "why doesn't he report it via the Contact Us page on the web server?" The answer is that the Contact Us page is protected by the same broken CAPTCHA.

So I am reporting it here on the off chance that whoever maintains this repo will have an interest in informing whoever is responsible for the web interface that they have a problem.

**Comment by Brian-Luke** [comment]
We fixed the CAPTCHA problem in the web version of non-BMST
